# Generated by Django 5.0.2 on 2024-03-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.BinaryField()),
                ('time', models.DateTimeField()),
                ('segment_len', models.PositiveIntegerField()),
                ('segment_num', models.PositiveIntegerField()),
            ],
        ),
    ]
